### ISSUE TITLE
clone does not change con and tap properties

### ISSUE THREAD

**Issue by MichaelAronsen** [pr1ntf/iohyve#97] opened 2016-01-15 02:01 UTC
When cloning a vm, all properties except name are cloned directly.

The con and tap properties should be reinitialized with new values, like when iohyve create is used, to avoid duplicate console and tap interfaces.

**Comment by pr1ntf** [comment] 2016-01-15 03:43
That's totally a feature not a bug. 

Just kidding. That's actually how I designed the clone function on purpose. At the time, I wanted to go back and take a second look on how `iohyve` handled command line input but I _REALLY_ wanted cloning. I left "using a command line option to make an exact clone or a replicated clone" until I figured something out. In the mean time, I only change the name and [description](https://github.com/pr1ntf/iohyve/blob/master/iohyve#L1071). 

You do make a good point, and `iohyve` has matured ever so slightly to the point where I should really be giving this option. I'll leave this open as an enhancement request or until I put it in the [raodmap](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0).

Thanks for you thoughts on the project!

**Comment by MichaelAronsen** [comment] 2016-01-15 10:34
I only read the docs carefully enough to see that it is intended after creating this bug.

My use case is to create a few template vm's and spin up a bunch of clones and then destroy them, rinse and repeat.

I might just have a look at implementing the functionality myself as I need it sooner rather than later as I want to stop using linux/kvm :)

Any thoughts on whether it should be an option to clone, the default for clone or have a new name?

**Comment by pr1ntf** [comment] 2016-01-15 16:26
Feel free! I think we should stick it in the same clone function, but `iohyve clone -c(opy)` or `iohyve clone -r(eplicate)` or something. I just want the ability to do either carbon copies or reinitialized copies, kind of like VirtualBox has.

**Comment by MichaelAronsen** [comment] 2016-01-15 17:05
Ok, i've implemented this now, if -c (or anything other than -r in fact) is
used, it's a carbon copy.

If -r is specified, values are reinitialized.

Also updated man and text file with description, along with iohyve help
text.

Attached is a patch created with git diff -p > patch.

On Fri, 15 Jan 2016 at 17:26 pr1ntf notifications@github.com wrote:

> Feel free! I think we should stick it in the same clone function, but iohyve
> clone -c(opy) or iohyve clone -r(eplicate) or something. I just want the
> ability to do either carbon copies or reinitialized copies, kind of like
> VirtualBox has.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pr1ntf/iohyve/issues/97#issuecomment-172006604.
> 
> ## 

Regards,
Michael

**Comment by pr1ntf** [comment] 2016-01-16 00:34
GitHub strips email attachments. :octopus: 

You can always submit a [Pull Request](https://github.com/pr1ntf/iohyve/pulls), though. :space_invader:

**Comment by MichaelAronsen** [comment] 2016-01-18 10:25
Ah ok, now I've learned a little more about git/github :)

On Sat, 16 Jan 2016 at 01:34 pr1ntf notifications@github.com wrote:

> GitHub strips email attachments. [image: :octopus:]
> 
> You can always submit a Pull Request
> https://github.com/pr1ntf/iohyve/pulls, though. [image: :space_invader:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pr1ntf/iohyve/issues/97#issuecomment-172136601.
> 
> ## 

Regards,
Michael

**Comment by pr1ntf** [comment] 2016-01-19 18:56
Closing and bringing discussion to #99

**Closed as completed by pr1ntf** 2016-01-19 18:56 UTC
Labels: enhancement
