### ISSUE TITLE
Starting wrong with almost identical guest names

### ISSUE THREAD

**Issue by mariusvw** [pr1ntf/iohyve#168] opened 2016-05-25 09:50 UTC
I have two guest created, one jira64 and one jira64-test

If you stop both and try to start the non test guest:

```
iohyve start jira64
```

You get the following error:

```
# iohyve start jira64
[: /iohyve/zroot: unexpected operator
Starting jira64... (Takes 15 seconds for FreeBSD guests)
```

The tricky part in this situation is that the guest 'jira64' starts with the volume of jira64-test.
After checking the source it seems to be caused by the check to get the guest information.

```
zfs list -H -t volume -o name | grep iohyve/jira64 | grep disk0 | cut -d '/' -f1-3
zroot/iohyve/jira64-test
zroot/iohyve/jira64
```

I'm not sure if disk0 should always be available, if so this could be resolved by adding it to the grep.

```
zfs list -H -t volume -o name | grep iohyve/jira64/disk0 | cut -d '/' -f1-3
```

Looking further into it if this is the right solution for all situations in the code.
Any suggestions are welcome of course.

**Comment by moogle19** [comment] 2016-05-25 12:28
Hi, 
it would be nice if you could checkout my PR #165 and test if it fixes your problem.

**Comment by pr1ntf** [comment] 2016-05-27 04:38
I have merged that PR, please try pulling down the latest GitHub code and giving it a try. 

I cannot reproduce this bug in the latest version from GitHub.

**Comment by mariusvw** [comment] 2016-05-27 07:31
Seems to solve this issue. Only I'd be careful with using literal tabs in code. I'm sure there is a nicer way to get the dataset.

Another thing I notice, `iohyve list` seems to take initial 19 seconds now and a second run about 3 seconds.
In the 0.7.5 both times are < 1 second.
I'll try to test some more today and maybe work on the code too.

**Comment by pr1ntf** [comment] 2016-05-27 08:23
Please open a separate issue for the `iohyve list` issue. I was seeing a slight performance **increase** on my machine. Would be interesting to compare notes on that. 

I'll be closing this out since you no longer are seeing an issue regarding the subject.

**Closed as completed by pr1ntf** 2016-05-27 08:23 UTC
Labels: bug

**Comment by moogle19** [comment] 2016-05-27 08:51
@mariusvw Yes, using literal tab characters is far from ideal, but I could not think (or google) of a better alternative, since the '-P' option for Perl Regex is not supported in FreeBSD's grep (or most other tools like `sed`).
I could use something like `egrep '[[:space:]]$name$'` which might be a little better, but `[[:space:]]` also matches whitespace, newlines, etc...

**Comment by mariusvw** [comment] 2016-05-27 10:04
@moogle19 I have 4 hours today for working on iohyve, I'll walk though your changes and try to build something which is a bit more ideal. So far the tests I have done all succeed. Nice work so far! :)

**Comment by pr1ntf** [comment] 2016-05-27 13:05
For sanity's sake, please keep comments on #165 **in** #165. 

Thanks!
