### ISSUE TITLE
'iohyve create' doesn't work correctly

### ISSUE THREAD

**Issue by moogle19** [pr1ntf/iohyve#172] opened 2016-05-28 12:20 UTC
`iohyve create` doesn't work without an explicit pool when no guest is present.

That was my fault ( introduced in #165 ), because I try to get the pool by looking for the first iohyve guest and take the same pool for the creation of the new one.

To fix this problem there are two (probably more) ways to fix it:
- Use the old method in create (grep for the first appearance of 'iohyve' in `zfs list`)
- Add a zfs attribute (like `iohyve=yes`) to all datasets used for iohyve and then search for that

The 'old' method should work in most cases, but can fail in edge cases like someone has a dataset for iohyve backups on another pool named: `anotherpool/iohyve-backups` which is not intended to be used for iohyve but the old method would use it to create the guest on it.

The 'zfs attribute' method would require the attribute to be present on the iohyve dataset, so there must be some kind of migration to support existing installations.
Like when no `iohyve:pool` attribute is found, try to find the pool with the 'old' method and add the attribute to it.

So what is the way to go?

**Comment by pr1ntf** [comment] 2016-05-28 12:50
I, too, have fallen victim to this trap. No worries. 

I say let's add the attribute. I have done similar things things in the past where we included a "fix me" function. I think there's still an archive of that on the wiki.

**Comment by pr1ntf** [comment] 2016-05-28 12:58
Input is highly appreciated from the peanut gallery.

**Comment by mariusvw** [comment] 2016-05-30 07:55
What would be the expected behaviour if you would have multiple datasets with the `iohyve=yes` set?

I can imagine that this would result in an unexpected behaviour.
The example you name your self is already a point of attention, what if you have 3 pools on a machine which one is the backup. Which pool would you decide to use if trying to detect, the attributes will be copied to the backup too in our backup system.

One of the main reasons I prefer to manual define the pool.

"If you pay with peanuts, you get monkeys."

**Comment by moogle19** [comment] 2016-05-30 09:01
Good point. Haven't thought about that.

So we need a good way to define a default pool or we have to make the pool argument during `create` required.

If we are using a property to define a dataset, we must make sure that it is unique on a machine.
It would be a possibility to set `iohyve=yes` (or `iohyve:default=yes` to be more expressive) in the setup command. When it is set on one pool, it is removed from the other (all other) dataset(s).
Also the clone command must remove it from the clone. 

I think it is a lot easier to have a default dataset then to specify it on every `create`.

**Comment by moogle19** [comment] 2016-05-30 09:32
The `create` command need some changes anyway, to support a guest to live in any dataset the user wants (see [Roadmap](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0)).
We should keep that at the back of our minds.
The changes I made in 'ioh-guest' should already allow that for most of the other commands.

**Comment by pr1ntf** [comment] 2016-06-02 03:37
I say let's use a default pool. Most setups only have one pool anyway. 

> "If you pay with peanuts, you get monkeys."

Lol, I love it.

**Comment by pr1ntf** [comment] 2016-06-11 21:58
So, when the user runs `iohyve setup pool=poolname` the first time, it's assumed that it's going to be their primary pool. 

Because of this, I added the following to the `__guest_create()` function:

```
if [ -z $pool ]; then
    local pool="$(zfs list -H | grep /iohyve/ISO | cut -f1 -d/)"
fi
```

I added this because I'm getting ready to submit `v0.7.6` to ports.

This fix doesn't need to stay, but it gets the job done.

**Comment by pr1ntf** [comment] 2016-06-21 00:20
If there are no more comments from the monkeys in the gallery, I'll go ahead and close this issue out. If you feel this solution is not enough, I have no problem reopening.

**Closed as completed by pr1ntf** 2016-06-21 00:20 UTC
Labels: bug, help wanted

**Comment by mariusvw** [comment] 2016-06-21 07:42
For now the solution is fine, the over all create process could be nicer, I'll try to work out a concept first to demonstrate my idea.

**Comment by pr1ntf** [comment] 2016-06-21 08:08
:+1:
